version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      NODE_ENV: production
      PORT: 3009
      HOSTNAME: "0.0.0.0"
